### ISSUE TITLE
分類モデルをDjango内にうつし、コマンドとして実行できるようにする

### ISSUE THREAD

**Issue by ysekky** [tkda-h3/naive_bayes_web_app#12]
分類モデルの作成がipython notebookで行っていますが、
こちらをdjango内にうつしてコマンドとして実行可能にしてみましょう

コマンドの作り方は以下を参考にしてみてください

https://docs.djangoproject.com/ja/1.10/howto/custom-management-commands/
http://tokibito.hatenablog.com/entry/20150915/1442248528

**Comment by tkda-h3** [comment]
分類器の作成はdjango内に移しましたが、pickleのデータをレポジトリのルートディレクトリに保存する点は変更していません。
プルリクのリンクです。#19

**Comment by ysekky** [comment]
少しPRにコメントしますね。
あと、他のissueでもそうですが２点お願いしたい点があります
- Pull RequestはReviewer(この場合は私)の確認をもらってからマージするようにしましょう。実際の業務での開発フローでもそうなります
- 今回issue側にPRのリンクを貼っていますが、基本的にissueのリンクをPRに貼るようにしてください。そのほうが相互の視認性があがります(このあたりは好みの問題ではありますが…)

**Comment by tkda-h3** [comment]
承知しました。

**Comment by ysekky** [comment]
コメントしました。今回のPRのコメント内容についてはFuture Workとして捉えておいてください。
(もし直してくれたら、その際はぜひコメントさせてもらいます！）
細かいですが業務として実装する際には必ずチェックされるポイントですので、留意してくれると助かります

**Comment by ysekky** [comment]
コマンドができていると思うので、コマンドの使い方をREADMEに追加するのもやっておきましょう〜

**Comment by tkda-h3** [comment]
README.mdの追加を終えました。

**Comment by tkda-h3** [comment]
#19 のコメントに従い修正しました。

**Comment by ysekky** [comment]
こちらマージされたらこのissueは閉じますね。
一旦課題としては終了で大丈夫です。
今後のFutureWorkとしていくつかissueを作っておきますので、興味があればトライしてみてください

**Comment by ysekky** [comment]
お疲れ様でした！
