### ISSUE TITLE
pythonを実行するパスによって、処理が失敗する

### ISSUE THREAD

**Issue by ysekky** [tkda-h3/naive_bayes_web_app#13]
例えば以下だとカテゴリ予測を実行できません

``` sh
$ mysite/manage.py runsever
```

理由は `os.path.abspath` はpythonを実行しているpathに依存するためです

https://github.com/tkda-h3/naive_bayes_web_app/blob/master/mysite/myapp/naive_bayes.py#L53

djangoのプロジェクトルートはここからとれます
https://github.com/tkda-h3/naive_bayes_web_app/blob/master/mysite/mysite/settings.py#L16

`settings.py` で設定したものは
`from django.conf import settings` から取得できます

以下参考になりますかね。
http://hideharaaws.hatenablog.com/entry/2014/12/14/005342

こちらを踏まえてファイルを参照する箇所を書き直してみてください

**Comment by tkda-h3** [comment]
settings.pyのBASE_DIRを利用したコードに書き換え、プルリクを作りマージしました。
該当するプルリクのリンクです。#20

**Comment by ysekky** [comment]
確認しました。 本issueはcloseします
