### ISSUE TITLE
.gitignoreを追加して不要なファイルを削除しましょう

### ISSUE THREAD

**Issue by ysekky** [tkda-h3/naive_bayes_web_app#7]
アプリを動かすのに不要なファイルが沢山追加されています

.gitignoreを設定して不要なファイルがcommitされないようにし、
git rmで削除しておきましょう。

githubがデフォルトで作ってくれるpython用のgitignoreはこちらです
https://github.com/github/gitignore/blob/master/Python.gitignore

こちらを追加して対象となるファイルを削除しましょう

**Comment by tkda-h3** [comment]
すでにマージしてしまったのですが、プルリクを作成しました。#14

**Comment by ysekky** [comment]
こちら確認しましたのでcloseします
