### ISSUE TITLE
未知のURLに対して予測できていない

### ISSUE THREAD

**Issue by ysekky** [tkda-h3/naive_bayes_web_app#8]
課題を再掲します

```
## 処理内容
- 1. フォームから記事URLを入力する。
- 2. 1で入力された記事URLのHTMLを取得し、それを元に、記事カテゴリを判定する。
- 3. 2で判定したカテゴリを画面に出力する。
```

本プロジェクトで行っている処理は2.のURLのHTMLを取得し記事カテゴリを取得するという処理ではなく、
すでに予測されたURLのカテゴリを保存したPickleを読み出すのみであるように思います
そのため未知のカテゴリに対して予測ができていません．

予測の処理自体をformの中に組み込んでください

**Comment by tkda-h3** [comment]
恐れながら、ご指摘の意図を把握致し兼ねましたので2点確認させて頂きます。

## その１

処理2.では記事URLのHTMLの取得は行っていますが、そのHTMLから記事カテゴリ名をパースすることは行っておりません。

`cvt_y_to_category_name.dump`にはPickleによって、既知のURLとそれに対応するカテゴリ名を呼び出すオブジェクトが保存されているのではなく、数字のラベルとそれに対応するカテゴリ名を呼び出すオブフェクトが保存されています。

`get_category_name`関数の挙動は以下の通りです。

```
1. 引数でURLを受け取り記事コンテンツのテキストをスクレイピングで抽出
2. Pickleで保存した分類器に必要なオブジェクトの読み出し
3. 2で読み出した分類器によって1のテキストを分類
4. 分類結果を返す
```

以上より入力されたURLが既知か否かに関わらずカテゴリを予測しております。

## その２

「未知のカテゴリ」という言葉の意図を把握致し兼ねました。「未知のURL」の誤りかと存じます。
以下は再掲された課題の続きです。

```
## 処理内容
- 1. フォームから記事URLを入力する。
- 2. 1で入力された記事URLのHTMLを取得し、それを元に、記事カテゴリを判定する。
- 3. 2で判定したカテゴリを画面に出力する。

2で使用する教師あり文書分類器は、事前に学習しておく必要があります。
教師データは、 https://gunosy.com/ の「エンタメ」、「スポーツ」、「おもしろ」、「国内」、「海外」、「コラム」、「IT・科学」、「グルメ」の記事を使用して下さい。
```

今回想定されているカテゴリは「エンタメ」、「スポーツ」、「おもしろ」、「国内」、「海外」、「コラム」、「IT・科学」、「グルメ」のみであり、それ以外のカテゴリに分類することは意図されていないものと存じます。

**Comment by ysekky** [comment]
申し訳ありません、こちら僕の実装の読み違えでした。
こちらcloseさせていただきます

**Comment by ysekky** [comment]
動作のほう確認して上記の指摘事項が問題なかったことを確認しました。
重ねて申し訳ありませんでした

**Comment by tkda-h3** [comment]
こちらこそ貴重なお時間を頂いてのご指摘に感謝申し上げます。
